$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: '0.2'
ignorePaths:
  - node_modules
  - pnpm-lock.yaml
  - dist
words:
  - AIRI
  - animejs
  - antfu
  - Azeret
  - clustr
  - esbuild
  - Fira
  - iconify
  - preflights
  - tsdown
  - vitejs
  - vitepress
  - vitest
  - unocss
  - nodenext
  - vite
  - npmjs
  - Attributify
  - Makito
  - क्षि
