$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
ignorePaths:
  - node_modules
words:
  - AIRI
  - animejs
  - antfu
  - Azeret
  - clustr
  - esbuild
  - Fira
  - iconify
  - preflights
  - tsdown
  - vitejs
  - vitepress
  - vitest
