packages:
  - packages/**
catalog:
  '@antfu/eslint-config': ^4.16.2
  '@iconify-json/ri': ^1.2.5
  '@tsconfig/strictest': ^2.0.5
  '@types/node': ^24.0.12
  '@unocss/preset-web-fonts': ^66.3.3
  '@unocss/reset': ^66.3.3
  '@vitejs/plugin-vue': ^6.0.0
  '@vue/tsconfig': ^0.7.0
  animejs: ^4.0.2
  cspell: ^9.1.3
  eslint: ^9.30.1
  tsdown: ^0.12.9
  typescript: ^5.8.3
  unocss: ^66.3.3
  vite: ^7.0.4
  vitest: ^3.2.4
  vue: ^3.5.17
  vue-tsc: ^2.2.12
onlyBuiltDependencies:
  - esbuild
