name: Build and Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    name: Check Source Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install asdf and tools
        uses: asdf-vm/actions/install@v4

      - name: Install dependencies
        run: pnpm install

      - name: Run cSpell
        uses: streetsidesoftware/cspell-action@v7

      - name: Lint
        run: pnpm run lint

  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install asdf and tools
        uses: asdf-vm/actions/install@v4

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Run tests
        run: pnpm run test
