name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  code-checks:
    name: Code checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install asdf and tools
        uses: asdf-vm/actions/install@v4

      - name: Inspect Node.js
        run: |
          which node
          node --version

      - name: Install dependencies
        run: pnpm install

      - name: Spellcheck
        run: pnpm run spellcheck

      - name: Lint
        run: pnpm run lint

  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install asdf and tools
        uses: asdf-vm/actions/install@v4

      - name: Inspect Node.js
        run: |
          which node
          node --version

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Run tests
        run: pnpm run test
