name: Build, Test, and Publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-test-publish:
    name: Build, Test, and Publish
    uses: ./.github/workflows/reusable-build-test-publish.yaml
    with:
      publish: true
