name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  code-checks:
    name: Code checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install asdf and tools
        uses: asdf-vm/actions/install@v4

      - name: Install dependencies
        run: asdf exec pnpm install

      - name: Run cSpell
        uses: streetsidesoftware/cspell-action@v7

      - name: Lint
        run: asdf exec pnpm run lint

  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install asdf and tools
        uses: asdf-vm/actions/install@v4

      - name: Install dependencies
        run: asdf exec pnpm install

      - name: Build
        run: asdf exec pnpm run build

      - name: Run tests
        run: asdf exec pnpm run test
