name: Build, Test, and Publish

on:
  workflow_call:
    inputs:
      publish:
        type: boolean
        required: false
        default: false

jobs:
  check:
    name: Run code checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install asdf and tools
        uses: asdf-vm/actions/install@v4

      - name: Inspect Node.js
        run: |
          which node
          node --version

      - name: Install dependencies
        run: pnpm install

      - name: Spellcheck
        run: pnpm run spellcheck

      - name: Lint
        run: pnpm run lint

  build-test-publish:
    name: Build, test, and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install asdf and tools
        uses: asdf-vm/actions/install@v4

      - name: Inspect Node.js
        run: |
          which node
          node --version

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Run tests
        run: pnpm run test

      - if: inputs.publish
        name: Publish package
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm run publish:lib
